# Generated by Django 4.0.1 on 2022-01-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0002_bug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('acitvity_description', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=50)),
            ],
        ),
    ]
