# Generated by Django 4.0.1 on 2022-01-11 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0003_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
            ],
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='acitvity_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='bug',
            old_name='project',
            new_name='project_id',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='bug',
            name='date',
        ),
        migrations.RemoveField(
            model_name='bug',
            name='description',
        ),
        migrations.RemoveField(
            model_name='bug',
            name='title',
        ),
        migrations.AddField(
            model_name='activity',
            name='bug_id',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='bugtracker.bug'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='date published')),
                ('tite', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugtracker.user')),
            ],
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugtracker.position')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugtracker.user')),
            ],
        ),
        migrations.CreateModel(
            name='BugAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugtracker.bug')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugtracker.user')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugtracker.project')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugtracker.user')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='user_id',
            field=models.ForeignKey(default=1234, on_delete=django.db.models.deletion.CASCADE, to='bugtracker.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bug',
            name='flag_id',
            field=models.ForeignKey(default=1234, on_delete=django.db.models.deletion.PROTECT, to='bugtracker.flag'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bug',
            name='report_id',
            field=models.ForeignKey(default=1234, on_delete=django.db.models.deletion.CASCADE, to='bugtracker.report'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bug',
            name='status_id',
            field=models.ForeignKey(default=1234, on_delete=django.db.models.deletion.PROTECT, to='bugtracker.status'),
            preserve_default=False,
        ),
    ]
