# Generated by Django 4.0.1 on 2022-01-11 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0004_flag_position_status_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='bug_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bugtracker.bug'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bugtracker.user'),
        ),
    ]
